# @see https://docs.docker.com/compose/compose-file/compose-file-v3/
# @see https://github.com/krallin/tini/issues/8
version: '3.7'
services:
  nginx:
    image: yoannisj/craft-nginx:${NGINX_VERSION:-1.19}
    build:
      dockerfile: ./docker/nginx/Dockerfile
      context: .
      args: # expose environment variables as build arguments
        - NGINX_VERSION
        - ENVIRONMENT
    env_file:
      # load environment variables from files listed below into Dockerfile and containers
      # @note environment variables in files lower down the list override values from previous files
      # @note variables defined in the service's 'environment' key override values from files
      - .env
    volumes:
      # we serve public static files via nginx directly
      - ./web:/var/www/html/web
    init: true # enables improved process management
    networks:
      - webnet # add service to the internal 'webnet' network (see 'networks' key below)
    ports:
      - '${PUBLIC_WEB_PORT:-80}:80'
      - '${PUBLIC_WEB_PORT_SECURE:-443}:443'
    depends_on:
      - php-web
  php-web: &php-service
    image: yoannisj/craft-php:${PHP_VERSION:-7.4}
    build:
      dockerfile: ./docker/php/Dockerfile
      context: .
      args: # expose environment variables as build arguments
        - PHP_VERSION=${PHP_VERSION:-7.4}
        - ENVIRONMENT=${ENVIRONMENT:-production}
    env_file:
      - .env
    environment:
      DATABASE_HOST: db
    volumes:
      - ./web:/var/www/html/web
      - ./craftcms/config:/var/www/html/craftcms/config
      - ./craftcms/modules:/var/www/html/craftcms/modules
      - ./craftcms/storage/backups:/var/www/html/craftcms/storage/backups
      - ./craftcms/templates:/var/www/html/craftcms/templates
      - ./vendor:/var/www/html/vendor
      - ./composer.json:/var/www/html/composer.json
      - ./composer.lock:/var/www/html/composer.lock
    init: true # enables improved process management
    command: ["php-fpm"]
    networks:
      - webnet # add service to the internal 'webnet' network (see 'networks' key below)
    expose:
      - '9000' # expose to internal networks via port 9000
    depends_on:
      - db
      - redis
  php-worker:
    <<: *php-service
    expose:
      - '9001' # expose to internal networks via port 9001
    command: [ "./run_craft_queue.sh" ]
  db:
    # extended by either docker-compose.mysql.yaml, docker-compose.mariadb.yml or docker-compose.postgres.yml
    build:
      context: .
      args: # expose environment variables as build arguments
        - ENVIRONMENT
    init: true # enables improved process management
    networks:
      - webnet # add service to the internal 'webnet' network (see 'networks' key below)
  redis:
    image: yoannisj/craft-redis:${REDIS_VERSION:-5}
    build:
      dockerfile: ./docker/redis/Dockerfile
      context: .
    init: true
    networks:
      - webnet
    ports:
      - '${PUBLIC_REDIS_PORT:-6379}:${REDIS_PORT:-6379}'
volumes:
  # we use named volumes to share and persist files and data across services, but without maintaining them as part of the project
  # those volumes are stored internally by docker
  dbdata:
    driver: local
networks:
  # create internal network called 'webnet' which used the default network driver 'bridge'
  webnet:
    driver: bridge
