# @see https://docs.docker.com/compose/compose-file/compose-file-v3/
# @see https://github.com/krallin/tini/issues/8
version: '3.7'
services:
  nginx:
    image: yoannisj/craft-nginx:${NGINX_VERSION:-1.19}
    build:
      dockerfile: ./services/nginx/Dockerfile
      context: .
      args: # expose environment variables as build arguments
        - ENVIRONMENT
        - NGINX_VERSION=${NGINX_VERSION:-1.19}
        - NGINX_ENVSUBST_TEMPLATE_SUFFIX=${NGINX_ENVSUBST_TEMPLATE_SUFFIX:-.template}
        - NGINX_ENVSUBST_TEMPLATE_DIR=${NGINX_ENVSUBST_TEMPLATE_DIR:-/etc/nginx/templates}
        - LOCAL_SSL_KEY_FILE=${LOCAL_SSL_KEY_FILE:-./services/ssl/private.key}
        - LOCAL_SSL_CERT_FILE=${LOCAL_SSL_CERT_FILE:-./services/ssl/public.crt}
        - WEB_ROOT=${WEB_ROOT:-/var/www/html/web}
        - WEB_HOSTNAME=${WEB_HOSTNAME:-localhost}
        - WEB_PORT=80
    env_file:
      # load environment variables from files listed below into Dockerfile and containers
      # @note environment variables in files lower down the list override values from previous files
      # @note variables defined in the service's 'environment' key override values from files
      - .env
    environment:
      TUNNEL_HOSTNAME: ${TUNNEL_HOSTNAME:-''}
      TUNNEL_PORT: ${TUNNEL_PORT:-''}
    volumes:
      # we serve public static files via nginx directly
      - ./services/ssl/localhost-mkcert-private.key:/etc/nginx/ssl/private.key
      - ./services/ssl/localhost-mkcert-public.crt:/etc/nginx/ssl/public.crt
      - ./web:/var/www/html/web
    init: true # enables improved process management
    networks:
      - craftnet # add service to the internal 'craftnet' network (see 'networks' key below)
    ports:
      - '${WEB_PORT:8080}:80'
      - '443:443'
    depends_on:
      - craft-web
    profiles:
      - web
  craft-web: &craft-service
    image: yoannisj/craft:${PHP_VERSION:-7.4}
    build:
      dockerfile: ./services/craft/Dockerfile
      context: .
      args: # expose environment variables as build arguments
      - ENVIRONMENT
      - PHP_VERSION
    env_file:
      - .env
    environment:
      DATABASE_HOSTNAME: db
    volumes:
      - ./composer.json:/var/www/html/composer.json
      - ./composer.lock:/var/www/html/composer.lock
      - ./vendor:/var/www/html/vendor
      - ./craftcms/config:/var/www/html/craftcms/config
      - ./craftcms/modules:/var/www/html/craftcms/modules
      - ./craftcms/storage/backups:/var/www/html/craftcms/storage/backups
      - ./craftcms/templates:/var/www/html/craftcms/templates
      - ./web:/var/www/html/web
    init: true # enables improved process management
    networks:
      - craftnet # add service to the internal 'craftnet' network (see 'networks' key below)
    depends_on:
      - db
      - redis
    command: [ "php-fpm" ]
    profiles:
      - web
  craft-cli:
    <<: *craft-service
    entrypoint: [ "php", "./craft" ]
    command: [ "help" ]
    profiles:
      - cli
  craft-queue:
    <<: *craft-service
    expose:
      - '9001' # expose to internal networks via port 9001
    command: [ "./craft_queue.sh" ]
    profiles:
      - web
      - cli
  db:
    # this service needs to be extended by loading one of the database service overrides:
    # - ./services/mysql/docker-compose.ovveride.yaml
    # - ./services/mariadb/docker-compose.override.yml
    # - ./services/postgres/docker-compose.override.yml
    build:
      context: .
      args: # expose environment variables as build arguments
        - ENVIRONMENT
    init: true # enables improved process management
    networks:
      - craftnet # add service to the internal 'craftnet' network (see 'networks' key below)
    profiles:
      - web
      - cli
  redis:
    image: yoannisj/craft-redis:${REDIS_VERSION:-5}
    build:
      dockerfile: ./services/redis/Dockerfile
      context: .
    init: true
    networks:
      - craftnet
    ports:
      - '${REDIS_PORT:-6379}${PUBLIC_PORT_SUFFIX}:${REDIS_PORT:-6379}'
    profiles:
      - web
      - cli
networks:
  # create internal network called 'craftnet' which used the default network driver 'bridge'
  craftnet: # network used by craft application services
    driver: bridge
