services:
  craft-web: &craft-service-mysql
    image: yoannisj/craft-mysql:${PHP_VERSION}
    build:
      args:
        - DATABASE_DRIVER=mysql
        - MYSQL_VERSION=${MYSQL_VERSION:-8.0}
    environment:
      DATABASE_DRIVER: mariadb
      DATABASE_VERSION: ${MYSQL_VERSION:-8.0}
  craft-cli:
    *craft-service-mysql
  craft-queue:
    *craft-service-mysql
  db:
    image: yoannisj/craft-db-mysql:${MYSQL_VERSION:-8.0}
    build:
      dockerfile: ./services/mysql/Dockerfile
      context: .
      args:
        - MYSQL_VERSION=${MYSQL_VERSION:-8.0}
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD:-secret}
      MYSQL_USER: ${DATABASE_USER:-craftcms}
      MYSQL_PASSWORD: ${DATABASE_USER:-secret}
      MYSQL_DATABASE: ${DATABASE_NAME:-craftcms}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - '${PUBLIC_DATABASE_PORT:-3306}:${DATABASE_PORT:-3306}'
volumes:
  # we use named volumes to share and persist files and data across services, but without
  # maintaining them as part of the project (these volumes are stored internally by docker)
  mysql_data:
    driver: local
