services:
  craft-web: &craft-service-postgres
    image: yoannisj/craft:${PHP_VERSION}-postgres
    build:
      dockerfile: ./services/craft/Dockerfile.postgres
      context: .
      args:
        - DATABASE_DRIVER=postgres
        - POSTGRES_VERSION=${POSTGRES_VERSION:-13.3}
    environment:
      DATABASE_DRIVER: postgres
      DATABASE_VERSION: ${POSTGRES_VERSION:-13.3}
  craft-cli:
    *craft-service-postgres
  craft-queue:
    *craft-service-postgres
  database:
    image: yoannisj/craft-db-postgres:${POSTGRES_VERSION:-13.3}
    build:
      dockerfile: ./services/database/postgres/Dockerfile
      context: .
      args:
        - POSTGRES_VERSION=${DATABASE_VERSION:-13.3}
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-craftcms}
      POSTGRES_USER: ${DATABASE_USER:-craftcms}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-secret}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - published: '${PUBLIC_PORT_PREFIX}${DATABASE_PORT:-5432}'
        target: '${DATABASE_PORT:-5432}'
volumes:
  # we use named volumes to share and persist files and data across services, but without
  # maintaining them as part of the project (these volumes are stored internally by docker)
  postgres_data:
    driver: local
